name: 📦 Publish NuGet Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🟣 Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 📦 Pack
        run: >
          dotnet pack 
          ./Projektanker.RazorComponents/Projektanker.RazorComponents.csproj
          --configuration Release

      - name: 🚀 Push
        run: >
          dotnet nuget push **.nupkg 
          --api-key ${{ secrets.NUGET_API_KEY }} 
          --source https://api.nuget.org/v3/index.json 
          --skip-duplicate
