name: ✨ Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: ✨ Release Please
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: Projektanker.RazorComponents
          extra-files: |
            Projektanker.RazorComponents/Projektanker.RazorComponents.csproj
          include-v-in-tag: false
