name: ✨ Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: ✨ Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.release_created }}
    steps:
      - name: ✨ Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: Projektanker.RazorComponents
          extra-files: |
            Projektanker.RazorComponents/Projektanker.RazorComponents.csproj
          include-v-in-tag: false

  publish:
    name: 📦 Publish NuGet Package
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: ${{ needs.release-please.release_created == true }}

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 🟣 Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 📦 Pack
        run: >
          dotnet pack 
          ./Projektanker.RazorComponents/Projektanker.RazorComponents.csproj
          --configuration Release

      - name: 🚀 Push
        run: >
          dotnet nuget push **.nupkg 
          --api-key ${{ secrets.NUGET_API_KEY }} 
          --source https://api.nuget.org/v3/index.json 
          --skip-duplicate
